import type { PlayerQueryBlock } from "../types";
import { humanizePlayerLinqField } from "../humanize";

const row = (linq: string) => ({ linq, label: humanizePlayerLinqField(linq) });

/** Stat sections from `AdvancedFilterUtils.playerLeaderBoardAutocomplete` that support rank/pctile where generated. */
export const playerQueryGradedStatBlocks: PlayerQueryBlock[] = [
  {
    id: "overall_ratings",
    title: "Overall ratings",
    includeRankPctile: true,
    fields: [
      "adj_rtg_margin",
      "adj_prod_margin",
      "adj_rapm_margin",
      "adj_rapm_prod_margin",
      "off_rtg",
      "off_adj_rtg",
      "off_adj_prod",
      "off_adj_rapm",
      "off_adj_rapm_prod",
      "def_rtg",
      "def_adj_rtg",
      "def_adj_prod",
      "def_adj_rapm",
      "def_adj_prod_rapm",
    ].map(row),
  },
  {
    id: "four_factors",
    title: "Four factors",
    includeRankPctile: true,
    fields: ["off_efg", "off_to", "off_ftr"].map(row),
  },
  {
    id: "shot_creation",
    title: "Shot creation",
    includeRankPctile: true,
    fields: [
      "off_usage",
      "off_assist",
      "off_ast_rim",
      "off_ast_mid",
      "off_ast_threep",
      "off_twoprimr",
      "off_twopmidr",
      "off_threepr",
    ].map(row),
  },
  {
    id: "shot_making",
    title: "Shot-making",
    includeRankPctile: true,
    fields: [
      "off_threep",
      "off_twop",
      "off_twopmid",
      "off_twoprim",
      "off_ft",
      "off_threep_ast",
      "off_twopmid_ast",
      "off_twoprim_ast",
    ].map(row),
  },
  {
    id: "rebounding_other",
    title: "Rebounding",
    includeRankPctile: true,
    fields: ["off_orb", "def_orb", "off_reb", "def_reb"].map(row),
  },
  {
    id: "defensive_stats",
    title: "Defensive Stats",
    includeRankPctile: true,
    fields: [
      { linq: "def_stl", label: "Def steal rate" },
      { linq: "def_blk", label: "Def block rate" },
      { linq: "def_fc", label: "Def foul called/50" },
    ],
  },
  {
    id: "opposition_strength",
    title: "Opposition strength",
    includeRankPctile: true,
    fields: ["off_adj_opp", "def_adj_opp"].map(row),
  },
  {
    id: "possessions",
    title: "Possessions",
    includeRankPctile: true,
    fields: [
      "off_poss",
      "off_team_poss_pct",
      "def_poss",
      "def_team_poss_pct",
    ].map(row),
  },
  {
    id: "scramble",
    title: "Scramble Stats",
    includeRankPctile: true,
    fields: [
      "off_scramble_twop",
      "off_scramble_threep",
      "off_scramble_threep_ast",
      "off_scramble_twoprim",
      "off_scramble_twoprim_ast",
      "off_scramble_twopmid",
      "off_scramble_twopmid_ast",
      "off_scramble_ft",
      "off_scramble_ftr",
      "off_scramble_twoprimr",
      "off_scramble_twopmidr",
      "off_scramble_threepr",
      "off_scramble_assist",
    ].map(row),
  },
  {
    id: "transition",
    title: "Transition Stats",
    includeRankPctile: true,
    fields: [
      "off_trans_twop",
      "off_trans_threep",
      "off_trans_threep_ast",
      "off_trans_twoprim",
      "off_trans_twoprim_ast",
      "off_trans_twopmid",
      "off_trans_twopmid_ast",
      "off_trans_ft",
      "off_trans_ftr",
      "off_trans_twoprimr",
      "off_trans_twopmidr",
      "off_trans_threepr",
      "off_trans_assist",
    ].map(row),
  },
  {
    id: "transfer_predictions",
    title: "Transfer predictions",
    includeRankPctile: true,
    fields: [
      "off_adj_rapm_pred",
      "def_adj_rapm_pred",
      "off_rtg_pred",
      "off_usage_pred",
      "adj_rapm_margin_pred",
    ].map(row),
  },
];
